routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// create link for Artisan command to optimize clear
Route::get('/linkoptimize', function () {
    Artisan::call('optimize:clear');
    return "Optimize Clear Done!";
});

Route::get('/linkstorage', function () {
    symlink('/home/mmdarsit/dev.mm3darsitektur.com/engine/storage/app/public',  '/home/mmdarsit/dev.mm3darsitektur.com/storage');
    return dd('Storage Link Created!');
});

//WEB PAGE ROUTING
Route::get('/','AdminController@home');
// Route::get('/project/{id_project}','AdminController@projectDetail');
Route::get('/projects', function() {
    return view('projects-view');
});

Route::get('/email', function() {
    return view('mail.html-template');
});

Route::get('/projects/{category}', function() {
    return view('projects-view');
});

//USERS ADMIN ROUTING
Route::get('/admin/login','AdminController@signin')->middleware('loggedin');
Route::get('/admin/register','AdminController@register');
Route::get('/admin/forgot','AdminController@forgotpass');
Route::get('/logout','AdminController@logout');

//ADMIN INTERFACE ROUTING
Route::get('/admin','AdminController@dashboard')->middleware('authuser');
Route::get('/admin/projects','AdminController@projectlist')->middleware('authuser');
Route::get('/admin/newproject','AdminController@addproject')->middleware('authuser');
Route::get('/admin/editproject/{id_project}','AdminController@editproject')->middleware('authuser');
Route::get('/admin/addprojectimage/{id_project}','AdminController@addprojectimage')->middleware('authuser');
Route::get('/admin/slideshow','AdminController@carousel')->middleware('authuser');
Route::get('/admin/newcarousel','AdminController@addcarousel')->middleware('authuser');
Route::get('/admin/category','AdminController@category')->middleware('authuser');
Route::get('/admin/newcategory','AdminController@newcategory')->middleware('authuser');
Route::get('/admin/sortcarousel/{orderNumber}/{oldNumber}/{newNumber}','AdminController@sortcarousel')->middleware('authuser');
Route::get('/admin/testimonial/','AdminController@viewTestimonial')->middleware('authuser');
Route::get('/admin/edittestimonial/{idTesti}','AdminController@getEditTestimonial')->middleware('authuser');
Route::get('/admin/editcontact/{id}','AdminController@getEditContactProfile')->middleware('authuser');
Route::get('/admin/editprofile','AdminController@getContactProfile')->middleware('authuser');
Route::get('/admin/clients','AdminController@viewClient')->middleware('authuser');
Route::get('/admin/editclients/{id}','AdminController@getClientById')->middleware('authuser');

//DATA
Route::post('/admin/storeproject', 'AdminController@storeproject')->middleware('authuser');
Route::post('/admin/storeeditproject/{id}','AdminController@storeEditProject')->middleware('authuser');
Route::get('/admin/removeProject','AdminController@removeProject')->middleware('authuser');
Route::post('/admin/registeruser', 'AdminController@registeruser');
Route::post('/admin/dologin', 'AdminController@dologin');
Route::get('/admin/setActive', 'AdminController@setActive')->name('/admin/setActive');
Route::get('/admin/setCarouselOrder', 'AdminController@setCarouselOrder')->name('/admin/setCarouselOrder');
Route::get('/admin/setCarouselActive', 'AdminController@setCarouselActive')->name('/admin/switchCarousel');
Route::get('/admin/removeCarousel', 'AdminController@removeCarousel')->name('/admin/deleteCarousel');
Route::post('/admin/uploadcarousel', 'AdminController@UploadCarousel');
Route::post('/admin/uploadcarouselTest', 'AdminController@UploadCarouselTest');
Route::post('/admin/addnewcategory','AdminController@addnewcategory');
Route::get('/admin/getCategoryById/{idCategory}','AdminController@getCategoryById');
Route::get('/admin/updateCategory/{idCategory}','AdminController@updateCategory')->middleware('authuser');
Route::get('/admin/removeCategory','AdminController@removeCategory')->name('/admin/removeCategory')->middleware('authuser');
Route::post('/admin/postimage','AdminController@addprojectimage');
Route::post('/admin/actionprojectimage','AdminController@actionprojectimage');
Route::post('/admin/storeTestimonial','AdminController@addTestimonial')->middleware('authuser');
Route::get('/admin/setTestimonialOrder', 'AdminController@setTestimonialOrder')->name('/admin/setTestiOrder');
Route::get('/admin/removeTestimonial', 'AdminController@removeTestimonial')->name('/admin/deleteTesti');
Route::get('/contactus','AdminController@sendEmail');
Route::get('/admin/updatetesti/{idTesti}','AdminController@updateTestimonial')->middleware('authuser');
Route::post('/admin/storeProfile','AdminController@addContactProfile')->middleware('authuser');
Route::get('/admin/edittestimonial/{idTesti}','AdminController@getEditTestimonial')->middleware('authuser');
Route::get('/admin/storeeditcontact/{id}','AdminController@storeEditContactProfile')->middleware('authuser');
Route::post('/admin/addNewClient','AdminController@addClient')->middleware('authuser');
Route::post('/admin/uploadClientLogo','AdminController@UploadClientImage')->middleware('authuser');
Route::get('/admin/getClient/{id}','AdminController@getClientById')->middleware('authuser');
Route::post('/admin/updateClient/{id}','AdminController@updateClient')->middleware('authuser');
Route::get('/admin/setClientOrder', 'AdminController@setClientOrder')->name('/admin/setClientOrder');
Route::get('/admin/toggleClientActive', 'AdminController@toggleClientActive')->name('/admin/toggleClient');
Route::get('/admin/removeClient', 'AdminController@deleteClient')->name('/admin/removeClient');

Route::post('/admin/fileuploader', 'AdminController@submit');
Route::post('/admin/ajax_remove_file', 'AdminController@removeFile');

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});

// Auth::routes();

app/Http/Controllers/ApiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Project;
use App\Models\Category;

class ApiController extends Controller
{
    public function getProjects() {
        $result = Project::where('project.is_deleted','=','0')
                    ->where('project.is_active','=','1')
                    ->where('category.is_deleted','=','0')
                    ->leftJoin('category', 'project.id_category', '=', 'category.id_category')
                    ->select('project.*', 'category.category_name', 'category.category_type', 'category.class')
                    ->get();
        
        return response()->json([
            'status' => 200,
            'data' => $result
        ]);
    }

    public function getProjectsByCategory($category) {
        $getCategoryByClassName = Category::where('class', '=', $category)->first();
        $categoryId = $getCategoryByClassName->id_category;

        $result = Project::where('project.is_deleted','=','0')
                    ->where('project.is_active','=','1')
                    ->where('category.is_deleted','=','0')
                    ->where('category.id_category','=',$categoryId)
                    ->leftJoin('category', 'project.id_category', '=', 'category.id_category')
                    ->select('project.*', 'category.category_name', 'category.category_type', 'category.class')
                    ->get();

        if(count($result)) {
            return response()->json([
                'status' => 200,
                'data' => $result
            ]);
        } else {
            return response()->json([
                'status' => 400,
                'data' => $result,
                'message' => 'not found'
            ]);
        }
    }

    public function getCategories() {
        $result = Category::where('is_deleted','=','0')->get();
        
        return response()->json([
            'status' => 200,
            'data' => $result
        ]);
    }
}

resources/views/admin/layout/header.blade.php
<!-- Search Bar -->
<div class="search-bar">
    <div class="search-icon">
        <i class="material-icons">search</i>
    </div>
    <input type="text" placeholder="START TYPING...">
    <div class="close-search">
        <i class="material-icons">close</i>
    </div>
</div>
<!-- #END# Search Bar -->

<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="/admin">MM3D Admin Page</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Call Search -->
                <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
                <!-- #END# Call Search -->
                <!-- Notifications -->
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <i class="material-icons">notifications</i>
                        <span class="label-count">7</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">NOTIFICATIONS</li>
                        <li class="body">
                            <ul class="menu">
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-light-green">
                                            <i class="material-icons">person_add</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>12 new members joined</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 14 mins ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-cyan">
                                            <i class="material-icons">add_shopping_cart</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>4 sales made</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 22 mins ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-red">
                                            <i class="material-icons">delete_forever</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4><b>Nancy Doe</b> deleted account</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 3 hours ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-orange">
                                            <i class="material-icons">mode_edit</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4><b>Nancy</b> changed name</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 2 hours ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-blue-grey">
                                            <i class="material-icons">comment</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4><b>John</b> commented your post</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 4 hours ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-light-green">
                                            <i class="material-icons">cached</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4><b>John</b> updated status</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 3 hours ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-purple">
                                            <i class="material-icons">settings</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>Settings updated</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> Yesterday
                                            </p>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="javascript:void(0);">View All Notifications</a>
                        </li>
                    </ul>
                </li>
                <!-- #END# Notifications -->
                <!-- Tasks -->
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <i class="material-icons">flag</i>
                        <span class="label-count">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">TASKS</li>
                        <li class="body">
                            <ul class="menu tasks">
                                <li>
                                    <a href="javascript:void(0);">
                                        <h4>
                                            Footer display issue
                                            <small>32%</small>
                                        </h4>
                                        <div class="progress">
                                            <div class="progress-bar bg-pink" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 32%">
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <h4>
                                            Make new buttons
                                            <small>45%</small>
                                        </h4>
                                        <div class="progress">
                                            <div class="progress-bar bg-cyan" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <h4>
                                            Create new dashboard
                                            <small>54%</small>
                                        </h4>
                                        <div class="progress">
                                            <div class="progress-bar bg-teal" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 54%">
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <h4>
                                            Solve transition issue
                                            <small>65%</small>
                                        </h4>
                                        <div class="progress">
                                            <div class="progress-bar bg-orange" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 65%">
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <h4>
                                            Answer GitHub questions
                                            <small>92%</small>
                                        </h4>
                                        <div class="progress">
                                            <div class="progress-bar bg-purple" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 92%">
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="javascript:void(0);">View All Tasks</a>
                        </li>
                    </ul>
                </li>
                <!-- #END# Tasks -->
                <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">more_vert</i></a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- #Top Bar -->

resources/views/admin/layout/template.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <title>@yield('title')</title>
        <!-- Favicon-->
        <link rel="icon" href="{{ URL::asset('cmsBSB/favicon.ico') }}" type="image/x-icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

        <link href="{{ URL::asset('/css/app.css') }}" rel="stylesheet">

        <!-- Bootstrap Core Css -->
        <link href="{{ URL::asset('cmsBSB/plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

        <!-- Waves Effect Css -->
        <link href="{{ URL::asset('cmsBSB/plugins/node-waves/waves.css') }}" rel="stylesheet" />

        <!-- Animation Css -->
        <link href="{{ URL::asset('cmsBSB/plugins/animate-css/animate.css') }}" rel="stylesheet" />

        <!-- Dropzone Css -->
        <link href="{{ URL::asset('cmsBSB/plugins/dropzone/dropzone.css') }}" rel="stylesheet">

        <!-- Bootstrap Material Datetime Picker Css -->
        <link href="{{ URL::asset('cmsBSB/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}" rel="stylesheet" />

        <!-- Bootstrap DatePicker Css -->
        <link href="{{ URL::asset('cmsBSB/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css') }}" rel="stylesheet" />

        <!-- Wait Me Css -->
        <link href="{{ URL::asset('cmsBSB/plugins/waitme/waitMe.css') }}" rel="stylesheet" />

        <!-- Morris Chart Css-->
        <link href="{{ URL::asset('cmsBSB/plugins/morrisjs/morris.css') }}" rel="stylesheet" />

        <!-- Bootstrap Select Css -->
        <link href="{{ URL::asset('cmsBSB/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />

        <!-- Custom Css -->
        <link href="{{ URL::asset('cmsBSB/css/style.css') }}" rel="stylesheet">

        <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
        <link href="{{ URL::asset('cmsBSB/css/themes/theme-teal.css') }}" rel="stylesheet" />

        <!-- Notification CSS -->
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-notify/0.2.0/css/bootstrap-notify.css">
        @yield('extraCSS')
    </head>
    <body class="theme-teal">
        <!-- Page Loader -->
        <div class="page-loader-wrapper">
            <div class="loader">
                <div class="preloader">
                    <div class="spinner-layer pl-red">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div>
                        <div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                </div>
                <p>Please wait...</p>
            </div>
        </div>
        <!-- #END# Page Loader -->
        <!-- Overlay For Sidebars -->
        <div class="overlay"></div>
        <!-- #END# Overlay For Sidebars -->

        @include('admin.layout.header')

        @include('admin.layout.sidebar')
        
        @yield('body')

        <!-- Jquery Core Js -->
        <!-- <script src="{{ URL::asset('cmsBSB/plugins/jquery/jquery.min.js') }}"></script> -->
        <script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>

        <!-- Bootstrap Core Js -->
        <!-- <script src="{{ URL::asset('cmsBSB/plugins/bootstrap/js/bootstrap.js') }}"></script> -->
        <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- Notification JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-notify/0.2.0/js/bootstrap-notify.js"></script>

        <!-- Select Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>

        <!-- Slimscroll Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

        <!-- Dropzone Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/dropzone/dropzone.js') }}"></script>

        <!-- Waves Effect Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/node-waves/waves.js') }}"></script>

        <!-- Autosize Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/autosize/autosize.js') }}"></script>

        <!-- Moment Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/momentjs/moment.js') }}"></script>

        <!-- Bootstrap Material Datetime Picker Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}"></script>

        <!-- Bootstrap Datepicker Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>

        <!-- Jquery CountTo Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/jquery-countto/jquery.countTo.js') }}"></script>

        <!-- Morris Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/raphael/raphael.min.js') }}"></script>
        <script src="{{ URL::asset('cmsBSB/plugins/morrisjs/morris.js') }}"></script>

        <!-- ChartJs -->
        <script src="{{ URL::asset('cmsBSB/plugins/chartjs/Chart.bundle.js') }}"></script>

        <!-- Flot Charts Plugin Js -->
        <!-- <script src="{{ URL::asset('cmsBSB/plugins/flot-charts/jquery.flot.resize.js') }}"></script>
        <script src="{{ URL::asset('cmsBSB/plugins/flot-charts/jquery.flot.pie.js') }}"></script>
        <script src="{{ URL::asset('cmsBSB/plugins/flot-charts/jquery.flot.categories.js') }}"></script>
        <script src="{{ URL::asset('cmsBSB/plugins/flot-charts/jquery.flot.js') }}"></script>
        <script src="{{ URL::asset('cmsBSB/plugins/flot-charts/jquery.flot.time.js') }}"></script> -->

        <!-- Sparkline Chart Plugin Js -->
        <script src="{{ URL::asset('cmsBSB/plugins/jquery-sparkline/jquery.sparkline.js') }}"></script>

        <!-- Custom Js -->
        <!-- <script src="{{ URL::asset('cmsBSB/js/pages/index.js') }}"></script> -->
        <script src="{{ URL::asset('cmsBSB/js/pages/forms/basic-form-elements.js') }}"></script>
        <script src="{{ URL::asset('cmsBSB/js/admin.js') }}"></script>
        

        @yield('script')
        <!-- Demo Js -->
        <script src="{{ URL::asset('cmsBSB/js/demo.js') }}"></script>
        @include('admin.dashboard.notification')
    </body>
</html>